#
# Docker services prepared for development purposes.
#
version: "3"
services:
  server:
    container_name: nginx
    image: nginx:1.14.0
    ports:
      - "8085:80"
    volumes:
      - ./../../:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
